
---
jobs:

- name: configure-pipeline
  serial_groups: [development,staging, production]
  plan:
  - in_parallel:
    - get: pipeline-source
      trigger: true
      params: {depth: 1}
  - set_pipeline: self
    file: pipeline-source/ci/pipeline.yml

- name: deploy-cspr-collector-development
  serial_groups: [development]
  plan:
  - in_parallel:
    - get: cspr-collector-app
      trigger: true
    - get: config-source
      trigger: true
  - put: create-es
    resource: cf-cli-dev
    params: &aws-es-params
      command: create-service
      update_service: true
      wait_for_service: true
      timeout: 1200  
      service_instance: cspr-collector-aws-es
      service: aws-elasticsearch
      plan: es-dev
  - put: deploy-cspr-collector-development
    params:
      manifest: config-source/manifest.yml
      path: cspr-collector-app
      current_app_name: cspr-collector
      var: route=cspr-collector.dev.us-gov-west-1.aws-us-gov.cloud.gov

- name: deploy-cspr-collector-staging
  serial_groups: [staging]
  plan:
  - in_parallel:
    - get: cspr-collector-app
      passed: 
      - deploy-cspr-collector-development
      trigger: true
    - get: config-source
      passed: 
      - deploy-cspr-collector-development
      trigger: true
  - put: create-es
    resource: cf-cli-staging
    params: 
      command: create-service
      update_service: true
      wait_for_service: true
      timeout: 1200  
      service_instance: cspr-collector-aws-es
      service: aws-elasticsearch
      plan: es-dev
  - put: deploy-cspr-collector-staging
    params:
      manifest: config-source/manifest.yml
      path: cspr-collector-app
      current_app_name: cspr-collector
      var: route=cspr-collector.fr-stage.cloud.gov

- name: deploy-cspr-collector-production
  serial_groups: [production]
  plan:
  - in_parallel:
    - get: cspr-collector-app
      passed: 
      - deploy-cspr-collector-staging
      trigger: true
    - get: config-source
      passed: 
      - deploy-cspr-collector-staging
      trigger: true
  - put: create-es
    resource: cf-cli-production
    params: 
      command: create-service
      update_service: true
      wait_for_service: true
      timeout: 1200  
      service_instance: cspr-collector-aws-es
      service: aws-elasticsearch
      plan: es-dev
  - put: deploy-cspr-collector-production
    params:
      manifest: config-source/manifest.yml
      path: cspr-collector-app
      current_app_name: cspr-collector
      var: route=cspr-collector.fr.cloud.gov


resources:

- name: pipeline-source
  type: git
  source:
    uri: https://github.com/cloud-gov/deploy-cspr-collector
    branch: inital-deploy
    paths: [ci/pipeline.yml]

- name: config-source
  type: git
  source:
    uri: https://github.com/cloud-gov/deploy-cspr-collector
    branch: inital-deploy

- name: cspr-collector-app
  type: git
  source:
    uri: https://github.com/soutenniza/cspr-collector

- name: deploy-cspr-collector-development
  type: cf
  source:
    api: https://api.dev.us-gov-west-1.aws-us-gov.cloud.gov
    username: ((development-cf-deployer.username))
    password: ((development-cf-deployer.password))
    organization: cloud-gov
    space: cspr-collector
    skip_cert_check: false

- name: cf-cli-dev
  type: cf-cli-resource
  source:
    api: https://api.dev.us-gov-west-1.aws-us-gov.cloud.gov
    username: ((development-cf-deployer.username))
    password: ((development-cf-deployer.password))
    org: cloud-gov
    space: cspr-collector

- name: deploy-cspr-collector-staging
  type: cf
  source:
    api: https://api.fr-stage.cloud.gov
    username: ((staging-cf-deployer.username))
    password: ((staging-cf-deployer.password))
    organization: cloud-gov
    space: cspr-collector
    skip_cert_check: false

- name: cf-cli-staging
  type: cf-cli-resource
  source:
    api: https://api.fr-stage.cloud.gov
    username: ((staging-cf-deployer.username))
    password: ((staging-cf-deployer.password))
    org: cloud-gov
    space: cspr-collector

- name: deploy-cspr-collector-production
  type: cf
  source:
    api: https://api.fr.cloud.gov
    username: ((production-cf-deployer.username))
    password: ((production-cf-deployer.password))
    organization: cloud-gov
    space: cspr-collector
    skip_cert_check: false

- name: cf-cli-production
  type: cf-cli-resource
  source:
    api: https://api.fr.cloud.gov
    username: ((production-cf-deployer.username))
    password: ((production-cf-deployer.password))
    org: cloud-gov
    space: cspr-collector


resource_types:
- name: cf-cli-resource
  type: docker-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: latest